name: navigator_resizable
description: >
  A thin wrapper around Navigator that *visually* resizes the child navigator
  to match the size of the content displayed in the current route.
version: 3.0.1
homepage: https://github.com/fujidaiti/navigator_resizable
topics:
  - ui
  - widget
  - navigation

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.29.0
  flutter_lints: ">=5.0.0 <7.0.0"
  mockito: ^5.4.5
  build_runner: ^2.4.14
